name: ChatProximity
main: ChatProximity\Main
api: 5.0.0
version: 2.0.0
author: AnasBex
description: Advanced proximity chat system for PMMP

permissions:
  chatproximity.toggle:
    description: Allow player to toggle proximity chat
    default: true
    
  chatproximity.bypass:
    description: Allow player to chat globally ignoring proximity
    default: op
    
  chatproximity.admin:
    description: Full admin access to ChatProximity features
    default: op

commands:
  togglechat:
    description: Enable/disable proximity chat
    usage: "/togglechat"
    permission: chatproximity.toggle