name: ChatProximity
main: ChatProximity\Main
api: 5.0.0
version: 1.1.0-Beta
author: AnasBex
description: Hybrid proximity chat system for PMMP

permissions:
  chatprox.bypass:
    description: Allow player to chat globally ignoring proximity
    default: op